services:
  company-db:
    container_name: company-db
    user: root
    image: bitnami/postgresql:16.1.0
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
    environment:
      - POSTGRESQL_DATABASE=${db:-company_db}
      - POSTGRESQL_PASSWORD=password123
      - PGPASSWORD=password123
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d ${db:-company_db}'"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 3s
    ports:
      - 10032:5432
    volumes:
      - .persistence/db:/bitnami/postgresql
    networks:
      - rdb
    logging:
      options:
        max-size: 10m
        max-file: "10"

  company-migrations:
    container_name: company-migrations
    user: ${UID:-1000}:${GID:-1000}
    image: ghcr.io/amacneil/dbmate:2.19
    depends_on:
      company-db:
        condition: service_healthy
    command: up
    env_file: ".env"
    volumes:
      - ./db:/db
    networks:
      - rdb
      
networks:
  rdb:
    name: rdb
    driver: bridge
