services:
  company-db:
    container_name: company-db
    user: root
    image: bitnami/postgresql:16.1.0
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
    environment:
      - POSTGRESQL_DATABASE=${db:-company_db}
      - POSTGRESQL_PASSWORD=password123
      - PGPASSWORD=password123
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d ${db:-company_db}'"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
    ports:
      - 11432:5432
    volumes:
      - .persistence/db:/bitnami/postgresql
    logging:
      options:
        max-size: 10m
        max-file: "10"
